# This file was generated by GoReleaser. DO NOT EDIT.
cask "wup" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "f2edfda55a75d94152ba8cb39e9b1578f9e5be69d0c09bc487985d793ded3db9"
      url "https://github.com/leblanck/wup/releases/download/v#{version}/wup_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b02e57530fbd9bc278295e018cf133387818271888214a9013812451c83ee6b2"
      url "https://github.com/leblanck/wup/releases/download/v#{version}/wup_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e2b2162019ce53e08c7fe734c5948c635c3ad4aaebbabdf096410f6aeb7003ba"
      url "https://github.com/leblanck/wup/releases/download/v#{version}/wup_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "117729b65e0cd55d3a024e199460cd78ee2c5d2dd470c0a100d56e1b93b4146d"
      url "https://github.com/leblanck/wup/releases/download/v#{version}/wup_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wup"
  desc "Terminal homepage dashboard: metrics, links, weather, Hacker News"
  homepage "https://github.com/leblanck/wup"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wup"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wup"]
    end
  end

  # No zap stanza required

end
