# This file was generated by GoReleaser. DO NOT EDIT.
cask "wup" do
  version "0.0.5"

  on_macos do
    on_intel do
      sha256 "1d3d7da7923331eccd9338595663b72d12af7cf9a4a0910ae3a118513ccef315"
      url "https://github.com/leblanck/wup/releases/download/v#{version}/wup_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "391ef4849d8d4a15a79a070ef2d9efcb48b9a14cd9b4b8c180308ecc89857647"
      url "https://github.com/leblanck/wup/releases/download/v#{version}/wup_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ff5e6bb10c719e8adc948d7969f39af9a5a102e69831bc67b8cee0bfbf039234"
      url "https://github.com/leblanck/wup/releases/download/v#{version}/wup_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "45df17fe1cbbd994f3bbc617c42e8c095ff82894ab87ce0650fc21c48afdc2ce"
      url "https://github.com/leblanck/wup/releases/download/v#{version}/wup_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wup"
  desc "Terminal homepage dashboard: metrics, links, weather, Hacker News"
  homepage "https://github.com/leblanck/wup"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wup"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wup"]
    end
  end

  # No zap stanza required

end
