# This file was generated by GoReleaser. DO NOT EDIT.
cask "wup" do
  version "0.0.4"

  on_macos do
    on_intel do
      sha256 "31aa56ebef385cd571fbe382eb4eb4f3ff57de7b0dd904bbb94e1b217458b565"
      url "https://github.com/leblanck/wup/releases/download/v#{version}/wup_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f55bfbe6b5d81b7a3e5a9db5472a44ab09e7c4e42e10e55e4ae9f6c56e89adc4"
      url "https://github.com/leblanck/wup/releases/download/v#{version}/wup_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7ef483caa30a841ef2eee2fef50d09cce14debb48806460c82e16ea01aa5afbc"
      url "https://github.com/leblanck/wup/releases/download/v#{version}/wup_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d00c6474c4e85421923920725dbe8bd2892e9283d58ae606b95eb7e4bd248027"
      url "https://github.com/leblanck/wup/releases/download/v#{version}/wup_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wup"
  desc "Terminal homepage dashboard: metrics, links, weather, Hacker News"
  homepage "https://github.com/leblanck/wup"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wup"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wup"]
    end
  end

  # No zap stanza required

end
