# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wup < Formula
  desc "Terminal homepage dashboard: metrics, links, weather, Hacker News"
  homepage "https://github.com/leblanck/wup"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leblanck/wup/releases/download/v0.0.1/wup_0.0.1_darwin_amd64.tar.gz"
      sha256 "4f19773c8a2ede2cf25aee7a9344d27ab51699f767b201dac63adf111d125602"

      define_method(:install) do
        bin.install "wup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leblanck/wup/releases/download/v0.0.1/wup_0.0.1_darwin_arm64.tar.gz"
      sha256 "749b30296ac0458ffb847399fc1755037ac155dcd67c63d84b9d6508156c876f"

      define_method(:install) do
        bin.install "wup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/leblanck/wup/releases/download/v0.0.1/wup_0.0.1_linux_amd64.tar.gz"
      sha256 "a711e4b4c5b5694792be4a3d6161a87824ec15b32cd6bb46b50b57c0e88df075"
      define_method(:install) do
        bin.install "wup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leblanck/wup/releases/download/v0.0.1/wup_0.0.1_linux_arm64.tar.gz"
      sha256 "ca9c41e99d66ac42d0ebd5fe35665a2c5108347a5e4098e9a870c09b41b63b2a"
      define_method(:install) do
        bin.install "wup"
      end
    end
  end

  test do
    assert_predicate bin/"wup", :exist?
  end
end
